# ===============================================================
# Color Scheme: Miasma
#
# Project: 1llicit-colors (Lbs-Archives)
# ------------------------------------
# Current Maintainer: LbsLightX (Expansion & Refactor)
# Original Logic: AvinashReddy3108 (Legacy 283 Themes)
#
# Source: https://github.com/Gogh-Co/Gogh
# Credits: https://github.com/Gogh-Co/Gogh/graphs/contributors
# ===============================================================

color0=#222222
color1=#685742
color2=#5f875f
color3=#b36d43
color4=#78824b
color5=#bb7744
color6=#c9a554
color7=#d7c483
color8=#666666
color9=#685742
color10=#5f875f
color11=#b36d43
color12=#78824b
color13=#bb7744
color14=#c9a554
color15=#d7c483

background=#222222
foreground=#c2c2b0
cursor=#c2c2b0
