# ===============================================================
# Color Scheme: Seoulism
#
# Project: 1llicit-colors (Lbs-Archives)
# ------------------------------------
# Current Maintainer: LbsLightX (Expansion & Refactor)
# Original Logic: AvinashReddy3108 (Legacy 283 Themes)
#
# Source: https://github.com/Gogh-Co/Gogh
# Credits: https://github.com/Gogh-Co/Gogh/graphs/contributors
# ===============================================================

color0=#101114
color1=#E94536
color2=#22D2B5
color3=#FF9F3E
color4=#2D5CE6
color5=#9C5CEB
color6=#2C9DD6
color7=#E0E0DC
color8=#242630
color9=#EE6962
color10=#53DCBA
color11=#FFC068
color12=#5B80EC
color13=#C680EF
color14=#5AB3DF
color15=#E7E7E4

background=#101114
foreground=#ECECE9
cursor=#ECECE9
